"""
    ExplainaBoard

    Backend APIs for ExplainaBoard  # noqa: E501

    The version of the OpenAPI document: 0.4.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import explainaboard_api_client
from explainaboard_api_client.model.system_metadata_updatable import SystemMetadataUpdatable
globals()['SystemMetadataUpdatable'] = SystemMetadataUpdatable
from explainaboard_api_client.model.system_update_props import SystemUpdateProps


class TestSystemUpdateProps(unittest.TestCase):
    """SystemUpdateProps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemUpdateProps(self):
        """Test SystemUpdateProps"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SystemUpdateProps()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
