"""
    ExplainaBoard

    Backend APIs for ExplainaBoard  # noqa: E501

    The version of the OpenAPI document: 0.4.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import explainaboard_api_client
from explainaboard_api_client.model.analysis import Analysis
from explainaboard_api_client.model.analysis_level import AnalysisLevel
from explainaboard_api_client.model.system_info_results import SystemInfoResults
from explainaboard_api_client.model.tokenizer import Tokenizer
globals()['Analysis'] = Analysis
globals()['AnalysisLevel'] = AnalysisLevel
globals()['SystemInfoResults'] = SystemInfoResults
globals()['Tokenizer'] = Tokenizer
from explainaboard_api_client.model.system_info import SystemInfo


class TestSystemInfo(unittest.TestCase):
    """SystemInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemInfo(self):
        """Test SystemInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SystemInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
