
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-17T05:53:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f3ae7f6a9cbb6e2fe7fe59c6a00cd7c6c5153cb",
 "version": "1.18.3.post0.dev33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
