# Generated by Django 3.2.2 on 2021-05-06 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=64, verbose_name='Pseudonym')),
                ('status', models.IntegerField(choices=[(0, 'Declined'), (1, 'Pending'), (2, 'Canceled'), (3, 'Finished')], default=0, verbose_name='Status')),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruitment.subjectgroup', verbose_name='Subject group')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
                'ordering': ('subject_group', 'status'),
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('end', models.DateTimeField(verbose_name='End')),
                ('status', models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Canceled'), (2, 'Finished')], default=0, verbose_name='Status')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.booking', verbose_name='Booking')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participations.participation', verbose_name='Participation')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ('participation', 'status'),
            },
        ),
    ]
