
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-02T22:02:55-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "58b57c2acea3b7dabb37087a9ddfbce9b0b9079c",
 "version": "0.1.3.dev20230416"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
