# Generated by Django 3.1.5 on 2021-01-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_play', '0003_videosplay_is_mark_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosplay',
            name='vr_projection',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('AUTO', 'AUTO'), ('180', '180'), ('360', '360'), ('Cube', 'Cube'), ('360_LR', '360_LR'), ('360_TB', '360_TB'), ('EAC', 'EAC'), ('EAC_LR', 'EAC_LR')], default='NONE', max_length=10, verbose_name='VR投影'),
        ),
    ]
