# Generated by Django 3.1.5 on 2021-06-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_play', '0005_auto_20210612_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosplay',
            name='hash',
            field=models.CharField(blank=True, help_text='sha256[哈希算法名字，统一用小写]:[分隔符]128[哈希]，最多字符数 136', max_length=136, null=True, verbose_name='Hash'),
        ),
        migrations.AddField(
            model_name='videosplay',
            name='sha1',
            field=models.CharField(blank=True, help_text='SHA-1 40位 预留 64 位字段', max_length=64, null=True, verbose_name='SHA1'),
        ),
    ]
