# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.1.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import obp_python
from obp_python.api.dynamic_api import DynamicApi  # noqa: E501
from obp_python.rest import ApiException


class TestDynamicApi(unittest.TestCase):
    """DynamicApi unit test stubs"""

    def setUp(self):
        self.api = obp_python.api.dynamic_api.DynamicApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dynamic_entity_create_mycustomers_favorite_alfh(self):
        """Test case for dynamic_entity_create_mycustomers_favorite_alfh

        Create new My Customers Favorite  # noqa: E501
        """
        pass

    def test_dynamic_entity_createcustomers_favorite_alfh(self):
        """Test case for dynamic_entity_createcustomers_favorite_alfh

        Create new Customers Favorite  # noqa: E501
        """
        pass

    def test_dynamic_entity_createcustomers_favorite_icecream_alfh(self):
        """Test case for dynamic_entity_createcustomers_favorite_icecream_alfh

        Create new Customers Favorite Icecream  # noqa: E501
        """
        pass

    def test_dynamic_entity_delete_mycustomers_favorite_alfh(self):
        """Test case for dynamic_entity_delete_mycustomers_favorite_alfh

        Delete My Customers Favorite by id  # noqa: E501
        """
        pass

    def test_dynamic_entity_deletecustomers_favorite_alfh(self):
        """Test case for dynamic_entity_deletecustomers_favorite_alfh

        Delete Customers Favorite by id  # noqa: E501
        """
        pass

    def test_dynamic_entity_deletecustomers_favorite_icecream_alfh(self):
        """Test case for dynamic_entity_deletecustomers_favorite_icecream_alfh

        Delete Customers Favorite Icecream by id  # noqa: E501
        """
        pass

    def test_dynamic_entity_get_mycustomers_favorite_list_alfh(self):
        """Test case for dynamic_entity_get_mycustomers_favorite_list_alfh

        Get My Customers Favorite List  # noqa: E501
        """
        pass

    def test_dynamic_entity_get_single_mycustomers_favorite_alfh(self):
        """Test case for dynamic_entity_get_single_mycustomers_favorite_alfh

        Get My Customers Favorite by id  # noqa: E501
        """
        pass

    def test_dynamic_entity_get_singlecustomers_favorite_alfh(self):
        """Test case for dynamic_entity_get_singlecustomers_favorite_alfh

        Get Customers Favorite by id  # noqa: E501
        """
        pass

    def test_dynamic_entity_get_singlecustomers_favorite_icecream_alfh(self):
        """Test case for dynamic_entity_get_singlecustomers_favorite_icecream_alfh

        Get Customers Favorite Icecream by id  # noqa: E501
        """
        pass

    def test_dynamic_entity_getcustomers_favorite_icecream_list_alfh(self):
        """Test case for dynamic_entity_getcustomers_favorite_icecream_list_alfh

        Get Customers Favorite Icecream List  # noqa: E501
        """
        pass

    def test_dynamic_entity_getcustomers_favorite_list_alfh(self):
        """Test case for dynamic_entity_getcustomers_favorite_list_alfh

        Get Customers Favorite List  # noqa: E501
        """
        pass

    def test_dynamic_entity_update_mycustomers_favorite_alfh(self):
        """Test case for dynamic_entity_update_mycustomers_favorite_alfh

        Update My Customers Favorite  # noqa: E501
        """
        pass

    def test_dynamic_entity_updatecustomers_favorite_alfh(self):
        """Test case for dynamic_entity_updatecustomers_favorite_alfh

        Update Customers Favorite  # noqa: E501
        """
        pass

    def test_dynamic_entity_updatecustomers_favorite_icecream_alfh(self):
        """Test case for dynamic_entity_updatecustomers_favorite_icecream_alfh

        Update Customers Favorite Icecream  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
