# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.1.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import obp_python
from obp_python.models.inline_response2012_customers_favorite import InlineResponse2012CustomersFavorite  # noqa: E501
from obp_python.rest import ApiException


class TestInlineResponse2012CustomersFavorite(unittest.TestCase):
    """InlineResponse2012CustomersFavorite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2012CustomersFavorite(self):
        """Test InlineResponse2012CustomersFavorite"""
        # FIXME: construct object with mandatory attributes with example values
        # model = obp_python.models.inline_response2012_customers_favorite.InlineResponse2012CustomersFavorite()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
