
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-19T17:33:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a95cd6a4410949053c8cb9bbb462c4bb46b4254e",
 "version": "23.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
