# Generated by Django 3.2.8 on 2023-04-18 18:14

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0074_productvariant_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="snooze_end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 18, 18, 13, 59, 234988, tzinfo=utc),
                help_text="When snooze status should end",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="snooze_start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 18, 18, 13, 59, 234926, tzinfo=utc),
                help_text="When snooze status should begin",
            ),
        ),
    ]
