from .text import Text


class EnglishText(Text):
    TEXTS = (
        "Today is one day.",
        "Today are two days.",
        "Today are three days.",
        "Today are four days.",
        "Today are five days.",
        "Today are six days.",
        "Today are seven days, which are one week.",
        "Today are eight days, which are one week and one day.",
        "Today are nine days, which are one week and two days.",
        "Today are ten days, which are one week and three days.",
        "Today are eleven days, which are one week and four days.",
        "Today are twelve days, which are one week and five days.",
        "Today are thirteen days, which are one week and six days.",
        "Today are fourteen days, which are two weeks.",
        "Today are fifteen days, which are two weeks and one day.",
        "Today are sixteen days, which are two weeks and two days.",
        "Today are seventeen days, which are two weeks and three days.",
        "Today are eighteen days, which are two weeks and four days.",
        "Today are nineteen days, which are two weeks and five days.",
        "Today are twenty days, which are two weeks and six days.",
        "Today are twenty-one days, which are three weeks.",
        "Today are twenty-two days, which are three weeks and one day.",
        "Today are twenty-three days, which are three weeks and two days.",
        "Today are twenty-four days, which are three weeks and three days.",
        "Today are twenty-five days, which are three weeks and four days.",
        "Today are twenty-six days, which are three weeks and five days.",
        "Today are twenty-seven days, which are three weeks and six days.",
        "Today are twenty-eight days, which are four weeks.",
        "Today are twenty-nine days, which are four weeks and one day.",
        "Today are thirty days, which are four weeks and two days.",
        "Today are thirty-one days, which are four weeks and three days.",
        "Today are thirty-two days, which are four weeks and four days.",
        "Today are thirty-three days, which are four weeks and five days.",
        "Today are thirty-four days, which are four weeks and six days.",
        "Today are thirty-five days, which are five weeks.",
        "Today are thirty-six days, which are five weeks and one day.",
        "Today are thirty-seven days, which are five weeks and two days.",
        "Today are thirty-eight days, which are five weeks and three days.",
        "Today are thirty-nine days, which are five weeks and four days.",
        "Today are forty days, which are five weeks and five days.",
        "Today are forty-one days, which are five weeks and six days.",
        "Today are forty-two days, which are six weeks.",
        "Today are forty-three days, which are six weeks and one day.",
        "Today are forty-four days, which are six weeks and two days.",
        "Today are forty-five days, which are six weeks and three days.",
        "Today are forty-six days, which are six weeks and four days.",
        "Today are forty-seven days, which are six weeks and five days.",
        "Today are forty-eight days, which are six weeks and six days.",
        "Today are forty-nine days, which are seven weeks.",
    )
    LAOMER = "of the Omer"
    END = "."
