# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/hc/Syf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1czepben/protobuf/hc/Syf.proto\x12\x12zepben.protobuf.hc\"5\n\x03Syf\x12\x10\n\x08scenario\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\x12\x0e\n\x06\x66\x65\x65\x64\x65r\x18\x03 \x01(\tB/\n\x16\x63om.zepben.protobuf.hcP\x01\xaa\x02\x12Zepben.Protobuf.HCb\x06proto3')



_SYF = DESCRIPTOR.message_types_by_name['Syf']
Syf = _reflection.GeneratedProtocolMessageType('Syf', (_message.Message,), {
  'DESCRIPTOR' : _SYF,
  '__module__' : 'zepben.protobuf.hc.Syf_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.hc.Syf)
  })
_sym_db.RegisterMessage(Syf)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.zepben.protobuf.hcP\001\252\002\022Zepben.Protobuf.HC'
  _SYF._serialized_start=52
  _SYF._serialized_end=105
# @@protoc_insertion_point(module_scope)
