
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-14T12:30:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ebb4a658ff675a707168ff89a0915c0a70c0ab86",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
