
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-18T13:02:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb5f5ae9aa54fdadbbc03908368cf2c04328329e",
 "version": "2.2.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
