# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.1.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from obp_python.configuration import Configuration


class Body13(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'customer': 'str',
        'car': 'str',
        'lucky_number': 'int'
    }

    attribute_map = {
        'customer': 'customer',
        'car': 'car',
        'lucky_number': 'lucky_number'
    }

    def __init__(self, customer=None, car=None, lucky_number=None, _configuration=None):  # noqa: E501
        """Body13 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._customer = None
        self._car = None
        self._lucky_number = None
        self.discriminator = None

        self.customer = customer
        self.car = car
        self.lucky_number = lucky_number

    @property
    def customer(self):
        """Gets the customer of this Body13.  # noqa: E501


        :return: The customer of this Body13.  # noqa: E501
        :rtype: str
        """
        return self._customer

    @customer.setter
    def customer(self, customer):
        """Sets the customer of this Body13.


        :param customer: The customer of this Body13.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and customer is None:
            raise ValueError("Invalid value for `customer`, must not be `None`")  # noqa: E501

        self._customer = customer

    @property
    def car(self):
        """Gets the car of this Body13.  # noqa: E501


        :return: The car of this Body13.  # noqa: E501
        :rtype: str
        """
        return self._car

    @car.setter
    def car(self, car):
        """Sets the car of this Body13.


        :param car: The car of this Body13.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and car is None:
            raise ValueError("Invalid value for `car`, must not be `None`")  # noqa: E501

        self._car = car

    @property
    def lucky_number(self):
        """Gets the lucky_number of this Body13.  # noqa: E501


        :return: The lucky_number of this Body13.  # noqa: E501
        :rtype: int
        """
        return self._lucky_number

    @lucky_number.setter
    def lucky_number(self, lucky_number):
        """Sets the lucky_number of this Body13.


        :param lucky_number: The lucky_number of this Body13.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and lucky_number is None:
            raise ValueError("Invalid value for `lucky_number`, must not be `None`")  # noqa: E501

        self._lucky_number = lucky_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body13, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body13):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Body13):
            return True

        return self.to_dict() != other.to_dict()
