
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-14T14:33:43+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "bff3b2f67be19fa55fdd209f5febcada76fcdc07",
 "version": "1.4.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
