
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-15T13:01:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a962b149b54a08dca9f16327b951d8a3870a001d",
 "version": "0.0.84"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
