
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-14T17:08:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "750b2a203c5f25b4c13e1cc1fc2e319388c324cd",
 "version": "2.2.48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
