
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-17T09:25:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4c9bd2a3e14df6c39baf8a2a1eb4992e67d52a7",
 "version": "2.2.49"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
