info = {"message": "ci: switch to psycopg2-binary==2.9.6 (arm64 fix)", "commit": "d284557185058a2ebf2cc739f7569584ee424214", "date": "2023/04/04 13:10:19", "branch": "", "version": "1.7.3+0.gd284557"}

# This file is automatically generated by version.py
# Do not include it to git!
