# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['uvicore',
 'uvicore.auth',
 'uvicore.auth.authenticators',
 'uvicore.auth.commands',
 'uvicore.auth.config',
 'uvicore.auth.contractsOLD',
 'uvicore.auth.database.seeders',
 'uvicore.auth.database.tables',
 'uvicore.auth.http.api',
 'uvicore.auth.http.routes',
 'uvicore.auth.middleware',
 'uvicore.auth.models',
 'uvicore.auth.support',
 'uvicore.auth.user_providers',
 'uvicore.cache',
 'uvicore.cache.backends',
 'uvicore.configuration',
 'uvicore.configuration.commands',
 'uvicore.console',
 'uvicore.console.asyncclick',
 'uvicore.console.commands',
 'uvicore.console.commands.stubs',
 'uvicore.console.events',
 'uvicore.container',
 'uvicore.container.commands',
 'uvicore.contracts',
 'uvicore.database',
 'uvicore.database.OBSOLETE',
 'uvicore.database.commands',
 'uvicore.database.commands.stubs',
 'uvicore.events',
 'uvicore.events.commands',
 'uvicore.exceptions',
 'uvicore.factories',
 'uvicore.foundation',
 'uvicore.foundation.commands',
 'uvicore.foundation.config',
 'uvicore.foundation.decorators',
 'uvicore.foundation.events',
 'uvicore.http',
 'uvicore.http.OBSOLETE',
 'uvicore.http.commands',
 'uvicore.http.commands.stubs',
 'uvicore.http.controllers',
 'uvicore.http.events',
 'uvicore.http.exceptions',
 'uvicore.http.middleware',
 'uvicore.http.openapi',
 'uvicore.http.routing',
 'uvicore.http.servers',
 'uvicore.http.templating',
 'uvicore.http_client',
 'uvicore.logging',
 'uvicore.mail',
 'uvicore.mail.backends',
 'uvicore.orm',
 'uvicore.orm.commands',
 'uvicore.orm.commands.stubs',
 'uvicore.orm.drivers',
 'uvicore.package',
 'uvicore.package.commands',
 'uvicore.redis',
 'uvicore.support',
 'uvicore.typing']

package_data = \
{'': ['*'], 'uvicore.auth': ['http/public/*', 'http/public/assets/js/*']}

install_requires = \
['aiohttp>=3.7.0,<3.8.0',
 'anyio>=3.2.0,<3.3.0',
 'argon2-cffi>=20.1.0,<20.2.0',
 'colored>=1.4.0,<1.5.0',
 'cryptography>=3.4.0,<3.5.0',
 'environs>=9.3.0,<9.4.0',
 'httpx>=0.19.0,<0.20.0',
 'merge-args>=0.1.0,<0.2.0',
 'prettyprinter>=0.18.0,<0.19.0']

extras_require = \
{'database': ['sqlalchemy>=1.3.0,<1.4.0',
              'alembic>=1.5.0,<1.6.0',
              'databases[mysql,postgresql,sqlite]>=0.4.0,<0.5.0',
              'pydantic>=1.8.0,<1.9.0'],
 'redis': ['aioredis>=1.3.0,<1.4.0'],
 'web': ['fastapi>=0.68.0,<0.69.0',
         'uvicorn>=0.13.0,<0.14.0',
         'gunicorn>=20.0.0,<20.1.0',
         'aiofiles>=0.6.0,<0.7.0',
         'Jinja2>=3.1.0,<3.2.0',
         'requests>=2.25.0,<2.26.0',
         'itsdangerous>=1.1.0,<1.2.0',
         'uvloop>=0.16.0,<0.17.0',
         'httptools>=0.1.0,<0.2.0',
         'python-multipart>=0.0.0,<0.1.0',
         'PyJWT>=2.0.0,<2.1.0']}

setup_kwargs = {
    'name': 'uvicore',
    'version': '0.1.25',
    'description': 'The Async Python Framework for Artisans. An Elegant Fullstack Python Web, API and CLI Framework',
    'long_description': '# Uvicore\n\nWelcome to Uvicore!  The Async Python Framework for Artisans. An Elegant Fullstack Python Web, API and CLI Framework.\n\n\n## Warning\n\nThis project is currently under heavy **active** development.  Although I am using this framework in Production personally, I am constantly building out the framework as I do. I would advise you against using it just yet.  It is mostly stable but **not feature complete**.\n\n\n## What is Uvicore?\n\n* A fullstack blazing fast asynchronous python Web, API and CLI framework.\n* Inspired by the elegance and design quality of Laravel.  Though it is NOT a Laravel clone by any stretch of the imagination.  If you want Laravel, go get Laravel and stop complaining about PHP :)\n* Not a mirco framework, up and running with a complete system in minutes, no boilerplate.\n* Deeply config driven with extremely deep merged and overridable package configs.\n* Package based.  Apps are packages, packages are apps.  No "shell" or "project" required.  Run it or use it in another running app, all in one.\n* Service Provider style package bootstrapping.\n* Full async database query builder built on encode/databases...or use the ORM!\n* Elegant custom async ORM inspired by Eloquent (but still very different).  Not another Django ORM clone thank God!\n* Complex and complete ORM relations including polymorphism.\n* Easy redis caching system (great for optimizing API database hits).\n* IoC (Inversion of Control).  Framework looks back to your app to determine import of every module.  You can override ANYTHING from core or other developers packages!\n* Blazing fast DUAL routers for Web and API usage, built on Starlette and FastAPI.\n* Perfectly suited for old-school server-side traditional post-back template driven web apps.\n* Perfectly suited for API backend only, quicker and easier that Django Rest Framework, built on FastAPI but with fullstack routing, controllers, ORM, caching...no boilerplate.\n* Websockets!  Well yeah, its async!\n* Automatic ORM Crud API\'s out of the box.  Never write a single controller or endpoint again.  Simply build Models. Instant API with granular roles and permission management.\n* ORM Models can query local database OR switch to remote API mode and query the data over uvicore automatic ORM crud APIs without code changing, syntax identical.  What?  This means your package IS the "server" and also the "client/sdk for API access".  Let that sink in a bit.\n* Granular groups, roles, permission management with Authentication middleware and route guards.\n* Quick and easy JWT authentication with an external IDP (FusionAuth!)\n* Multiple middleware authenticators.  APIs can autodetect and respond to Basic Auth, Digest, JWT and more.\n* Automatic OpenAPI 3.0 generated documentation for all API routes include automatic model router.\n* Fully async CLI based on asyncclick.  Query async ORM models and jobs from the CLI exactly as you would from an async web controller.  Everything can call async methods!\n* Event pub/sub system.  Subscribe to all Uvicore core events in the bootstrap process, ORM CRUD, authentication systems and any event fired from your packages.\n* And much more....documentation to come soon!\n\n\n\n## Feeling Dangerous?\n\nThis `uvicore/framework` repo is NOT what you clone if you want to run uvicore.  This is the framework.  The pypi package your actual app will depend on.  The `uvicore-installer` will create the folder structure for your app and include `uvicore/framework` as a dependency.  If you wanted to see what an app structure looks like, see https://github.com/uvicore/app which is what the `uvicore-installer` clones and regexes to your configured needs.  Its a package schematic.  **Use the installer.**\n\nIt works with a full installer, but there is little documentation yet so its up to you to deduce the system, though it\'s reasonably self explanatory.\n\n**Installation**\n```bash\nwget https://raw.githubusercontent.com/uvicore/framework/master/bin/uvicore-installer\nmv uvicore-installer /usr/local/bin\nchmod a+x /usr/local/bin/uvicore-installer\n\ncd ~/Code\nuvicore-installer  # To see help\nuvicore-installer ./blog\n\n# Follow the post-installation instructions\n# Review your .env\n# Review all configs\n# Download this https://github.com/uvicore/framework code and review the guts since there are\n# no docs yet :)  Look in the tests/apps/app1 folder for a small test app to glean how to use\n# it. Sorry, it\'s not done yet, but working hard on it!\n```\n\n\n## Stable v1.0 Roadmap\n\nI am tracking issues and enhancements for v1.0 in the Issues Milestones (and on a million sticky notes).  Before this project can be considered ready for public use I need to complete the following:\n\n* Proof the system by finishing several Production sites, APIs and CLIs at my current company.\n* Write far more tests and attempt 100% coverage\n* Build the main website at https://uvicore.io\n* Complete elegant documentation (ever read Laravels docs?  Like that.) at https://docs.uvicore.io\n\n\n\n## License\n\nThe Uvicore framework is open-sourced software licensed under the MIT license.\n',
    'author': 'Matthew Reschke',
    'author_email': 'mail@mreschke.com',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://github.com/uvicore/framework',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'extras_require': extras_require,
    'python_requires': '>=3.7,<4.0',
}


setup(**setup_kwargs)
