from .text import Text


class PhoneticHebrewText(Text):
    TEXTS = (
        "HaYom yom echad:",
        "HaYom shnei yamim:",
        "HaYom shlosha yamim:",
        "HaYom arba'a yamim:",
        "HaYom chamisha yamim:",
        "HaYom shisha yamim:",
        "HaYom shiv'a yamim, shehem shavua echad:",
        "HaYom shmona yamim, shehem shavua echad ve'yom echad:",
        "HaYom tish'a yamim, shehem shavua echad ushnei yamim:",
        "HaYom asara yamim, shehem shavua echad ushlosha yamim:",
        "HaYom achad asar yom, shehem shavua echad ve'arba'a yamim:",
        "HaYom shneim asar yom, shehem shavua echad vachamisha yamim:",
        "HaYom shlosha asar yom, shehem shavua echad veshisha yamim:",
        "HaYom arba'a asar yom, shehem shnei shavuot:",
        "HaYom chamisha asar yom, shehem shnei shavuot ve'yom echad:",
        "HaYom shisha asar yom, shehem shnei shavuot ushnei yamim:",
        "HaYom sheva asar yom, shehem shnei shavuot ushlosha yamim:",
        "HaYom shmona asar yom, shehem shnei shavuot ve'arba'a yamim:",
        "HaYom tish'a asar yom, shehem shnei shavuot vachamisha yamim:",
        "HaYom esrim yom, shehem shnei shavuot veshisha yamim:",
        "HaYom achad ve'esrim yom, shehem shlosha shavuot:",
        "HaYom shnaim ve'esrim yom, shehem shlosha shavuot ve'yom echad:",
        "HaYom shlosha ve'esrim yom, shehem shlosha shavuot ushnei yamim:",
        "HaYom arba'a ve'esrim yom, shehem shlosha shavuot ushlosha yamim:",
        "HaYom chamisha ve'esrim yom, shehem shlosha shavuot ve'arba'a yamim:",
        "HaYom shisha ve'esrim yom, shehem shlosha shavuot vachamisha yamim:",
        "HaYom sheva ve'esrim yom, shehem shlosha shavuot veshisha yamim:",
        "HaYom shmona ve'esrim yom, shehem arba'a shavuot:",
        "HaYom tish'a ve'esrim yom, shehem arba'a shavuot ve'yom echad:",
        "HaYom shloshim yom, shehem arba'a shavuot ushnei yamim:",
        "HaYom achad ushloshim yom, shehem arba'a shavuot ushlosha yamim:",
        "HaYom shnaim ushloshim yom, shehem arba'a shavuot ve'arba'a yamim:",
        "HaYom shlosha ushloshim yom, shehem arba'a shavuot vachamisha yamim:",
        "HaYom arba'a ushloshim yom, shehem arba'a shavuot veshisha yamim:",
        "HaYom chamisha ushloshim yom, shehem chamisha shavuot:",
        "HaYom shisha ushloshim yom, shehem chamisha shavuot ve'yom echad:",
        "HaYom sheva ushloshim yom, shehem chamisha shavuot ushnei yamim:",
        "HaYom shmona ushloshim yom, shehem chamisha shavuot ushlosha yamim:",
        "HaYom tish'a ushloshim yom, shehem chamisha shavuot ve'arba'a yamim:",
        "HaYom arbaim yom, shehem chamisha shavuot vachamisha yamim:",
        "HaYom achad ve'arbaim yom, shehem chamisha shavuot veshisha yamim:",
        "HaYom shnaim ve'arbaim yom, shehem shisha shavuot:",
        "HaYom shlosha ve'arbaim yom, shehem shisha shavuot ve'yom echad:",
        "HaYom arba'a ve'arbaim yom, shehem shisha shavuot ushnei yamim:",
        "HaYom chamisha ve'arbaim yom, shehem shisha shavuot ushlosha yamim:",
        "HaYom shisha ve'arbaim yom, shehem shisha shavuot ve'arba'a yamim:",
        "HaYom sheva ve'arbaim yom, shehem shisha shavuot vachamisha yamim:",
        "HaYom shmona ve'arbaim yom, shehem shisha shavuot veshisha yamim:",
        "HaYom tish'a ve'arbaim yom, shehem shiv'a shavuot:",
    )
    LAOMER = "laomer"
