
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-17T19:31:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f03e3ebc58f2b25cdbe895e695facbeb1d31708d",
 "version": "0.53.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
