# coding: utf-8

"""
    RIME Rest API

    API methods for RIME. Must be authenticated with `rime-api-key` header.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: dev@robustintelligence.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TestrunTestCategory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'TestrunTestCategoryType',
        'run_st': 'bool',
        'run_ct': 'bool'
    }

    attribute_map = {
        'type': 'type',
        'run_st': 'runSt',
        'run_ct': 'runCt'
    }

    def __init__(self, type=None, run_st=None, run_ct=None):  # noqa: E501
        """TestrunTestCategory - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._run_st = None
        self._run_ct = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if run_st is not None:
            self.run_st = run_st
        if run_ct is not None:
            self.run_ct = run_ct

    @property
    def type(self):
        """Gets the type of this TestrunTestCategory.  # noqa: E501


        :return: The type of this TestrunTestCategory.  # noqa: E501
        :rtype: TestrunTestCategoryType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TestrunTestCategory.


        :param type: The type of this TestrunTestCategory.  # noqa: E501
        :type: TestrunTestCategoryType
        """

        self._type = type

    @property
    def run_st(self):
        """Gets the run_st of this TestrunTestCategory.  # noqa: E501

        Specifies whether to run this test in Stress Testing.  # noqa: E501

        :return: The run_st of this TestrunTestCategory.  # noqa: E501
        :rtype: bool
        """
        return self._run_st

    @run_st.setter
    def run_st(self, run_st):
        """Sets the run_st of this TestrunTestCategory.

        Specifies whether to run this test in Stress Testing.  # noqa: E501

        :param run_st: The run_st of this TestrunTestCategory.  # noqa: E501
        :type: bool
        """

        self._run_st = run_st

    @property
    def run_ct(self):
        """Gets the run_ct of this TestrunTestCategory.  # noqa: E501

        Specifies whether to run this test in Continuous Testing.  # noqa: E501

        :return: The run_ct of this TestrunTestCategory.  # noqa: E501
        :rtype: bool
        """
        return self._run_ct

    @run_ct.setter
    def run_ct(self, run_ct):
        """Sets the run_ct of this TestrunTestCategory.

        Specifies whether to run this test in Continuous Testing.  # noqa: E501

        :param run_ct: The run_ct of this TestrunTestCategory.  # noqa: E501
        :type: bool
        """

        self._run_ct = run_ct

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TestrunTestCategory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestrunTestCategory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
