
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-17T04:19:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc5153f0b3ee43f65de57716009c799ba36dca3a",
 "version": "1.18.3.post0.dev21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
