
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-17T08:14:30-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "25c7fd1394c217b8282afaf93949bd34d2329e80",
 "version": "v1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
