# Generated by Django 3.2.8 on 2023-04-18 18:57

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0075_auto_20230418_2114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="snooze_end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 18, 18, 57, 10, 743048, tzinfo=utc),
                help_text="When snooze status should end",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="snooze_start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 18, 18, 57, 10, 742977, tzinfo=utc),
                help_text="When snooze status should begin",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="extra_infos",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
