
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-17T06:13:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef547aec4ba7ddc520f86934865846773d86ba3c",
 "version": "1.18.3.post0.dev36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
