
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-17T05:06:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0207556e608f703f2fffaf64d7f6a78eba371447",
 "version": "1.18.3.post0.dev27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
