# coding: utf-8

"""
    Clever Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import clever_client
from clever_client.api.users_api import UsersApi  # noqa: E501
from clever_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = clever_client.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_contacts_for_user(self):
        """Test case for get_contacts_for_user

        """
        pass

    def test_get_district_for_user(self):
        """Test case for get_district_for_user

        """
        pass

    def test_get_resources_for_user(self):
        """Test case for get_resources_for_user

        """
        pass

    def test_get_schools_for_user(self):
        """Test case for get_schools_for_user

        """
        pass

    def test_get_sections_for_user(self):
        """Test case for get_sections_for_user

        """
        pass

    def test_get_students_for_user(self):
        """Test case for get_students_for_user

        """
        pass

    def test_get_teachers_for_user(self):
        """Test case for get_teachers_for_user

        """
        pass

    def test_get_user(self):
        """Test case for get_user

        """
        pass

    def test_get_users(self):
        """Test case for get_users

        """
        pass


if __name__ == '__main__':
    unittest.main()
