# coding: utf-8

"""
    Clever Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import clever_client
from clever_client.models.staff import Staff  # noqa: E501
from clever_client.rest import ApiException


class TestStaff(unittest.TestCase):
    """Staff unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStaff(self):
        """Test Staff"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever_client.models.staff.Staff()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
