# coding: utf-8

"""
    Clever Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import clever_client
from clever_client.models.student import Student  # noqa: E501
from clever_client.rest import ApiException


class TestStudent(unittest.TestCase):
    """Student unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudent(self):
        """Test Student"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever_client.models.student.Student()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
