
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-19T21:07:25+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "fedff3b8983a5093e136043355f8aa7614713772",
 "version": "0.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
