# coding: utf-8

"""
    Clever Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from clever_client.configuration import Configuration


class DistrictContact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'title': 'str',
        'district': 'str',
        'email': 'str',
        'name': 'Name'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'district': 'district',
        'email': 'email',
        'name': 'name'
    }

    def __init__(self, id=None, title=None, district=None, email=None, name=None, _configuration=None):  # noqa: E501
        """DistrictContact - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._title = None
        self._district = None
        self._email = None
        self._name = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if title is not None:
            self.title = title
        if district is not None:
            self.district = district
        if email is not None:
            self.email = email
        if name is not None:
            self.name = name

    @property
    def id(self):
        """Gets the id of this DistrictContact.  # noqa: E501


        :return: The id of this DistrictContact.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DistrictContact.


        :param id: The id of this DistrictContact.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this DistrictContact.  # noqa: E501


        :return: The title of this DistrictContact.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this DistrictContact.


        :param title: The title of this DistrictContact.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def district(self):
        """Gets the district of this DistrictContact.  # noqa: E501


        :return: The district of this DistrictContact.  # noqa: E501
        :rtype: str
        """
        return self._district

    @district.setter
    def district(self, district):
        """Sets the district of this DistrictContact.


        :param district: The district of this DistrictContact.  # noqa: E501
        :type: str
        """

        self._district = district

    @property
    def email(self):
        """Gets the email of this DistrictContact.  # noqa: E501


        :return: The email of this DistrictContact.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this DistrictContact.


        :param email: The email of this DistrictContact.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def name(self):
        """Gets the name of this DistrictContact.  # noqa: E501


        :return: The name of this DistrictContact.  # noqa: E501
        :rtype: Name
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DistrictContact.


        :param name: The name of this DistrictContact.  # noqa: E501
        :type: Name
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DistrictContact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DistrictContact):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DistrictContact):
            return True

        return self.to_dict() != other.to_dict()
