# coding: utf-8

"""
    Clever Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from clever_client.configuration import Configuration


class DistrictAdmin(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'legacy_id': 'str',
        'title': 'str'
    }

    attribute_map = {
        'legacy_id': 'legacy_id',
        'title': 'title'
    }

    def __init__(self, legacy_id=None, title=None, _configuration=None):  # noqa: E501
        """DistrictAdmin - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._legacy_id = None
        self._title = None
        self.discriminator = None

        if legacy_id is not None:
            self.legacy_id = legacy_id
        if title is not None:
            self.title = title

    @property
    def legacy_id(self):
        """Gets the legacy_id of this DistrictAdmin.  # noqa: E501


        :return: The legacy_id of this DistrictAdmin.  # noqa: E501
        :rtype: str
        """
        return self._legacy_id

    @legacy_id.setter
    def legacy_id(self, legacy_id):
        """Sets the legacy_id of this DistrictAdmin.


        :param legacy_id: The legacy_id of this DistrictAdmin.  # noqa: E501
        :type: str
        """

        self._legacy_id = legacy_id

    @property
    def title(self):
        """Gets the title of this DistrictAdmin.  # noqa: E501


        :return: The title of this DistrictAdmin.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this DistrictAdmin.


        :param title: The title of this DistrictAdmin.  # noqa: E501
        :type: str
        """

        self._title = title

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DistrictAdmin, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DistrictAdmin):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DistrictAdmin):
            return True

        return self.to_dict() != other.to_dict()
