
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-17T13:30:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b23334a90f0f160c8f56facc014e67100b94db48",
 "version": "v1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
