problems = {
    'arrays & hashing': [
        'https://leetcode.com/problems/group-anagrams/',
        'https://leetcode.com/problems/top-k-frequent-elements/',
        'https://leetcode.com/problems/product-of-array-except-self/',
        'https://leetcode.com/problems/valid-sudoku/',
        'https://leetcode.com/problems/longest-consecutive-sequence/',
    ],
    'two pointers': [
        'https://leetcode.com/problems/valid-palindrome/',
        'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',
        'https://leetcode.com/problems/3sum/',
        'https://leetcode.com/problems/container-with-most-water/',
        'https://leetcode.com/problems/trapping-rain-water/',
    ],
    'sliding window': [
        'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
        'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
        'https://leetcode.com/problems/permutation-in-string/',
        'https://leetcode.com/problems/minimum-window-substring/',
        'https://leetcode.com/problems/sliding-window-maximum/',
    ],
    'stack': [
        'https://leetcode.com/problems/valid-parentheses/',
        'https://leetcode.com/problems/min-stack/',
        'https://leetcode.com/problems/generate-parentheses/',
        'https://leetcode.com/problems/daily-temperatures/',
        'https://leetcode.com/problems/car-fleet/',
        'https://leetcode.com/problems/largest-rectangle-in-histogram/',
    ],
    'binary search': [
        'https://leetcode.com/problems/binary-search/',
        'https://leetcode.com/problems/search-a-2d-matrix/',
        'https://leetcode.com/problems/koko-eating-bananas/',
        'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
        'https://leetcode.com/problems/search-in-rotated-sorted-array/',
        'https://leetcode.com/problems/time-based-key-value-store/',
        'https://leetcode.com/problems/median-of-two-sorted-arrays/',
    ],
    'linked list': [
        'https://leetcode.com/problems/reverse-linked-list/',
        'https://leetcode.com/problems/merge-two-sorted-lists/',
        'https://leetcode.com/problems/reorder-list/',
        'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
        'https://leetcode.com/problems/copy-list-with-random-pointer/',
        'https://leetcode.com/problems/add-two-numbers/',
        'https://leetcode.com/problems/linked-list-cycle/',
        'https://leetcode.com/problems/find-the-duplicate-number/',
    ],
    'trees': [
        'https://leetcode.com/problems/invert-binary-tree/',
        'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
        'https://leetcode.com/problems/diameter-of-binary-tree/',
        'https://leetcode.com/problems/balanced-binary-tree/',
        'https://leetcode.com/problems/same-tree/',
        'https://leetcode.com/problems/subtree-of-another-tree/',
        'https://leetcode.com/problems/binary-tree-level-order-traversal/',
        'https://leetcode.com/problems/binary-tree-right-side-view/',
        'https://leetcode.com/problems/count-good-nodes-in-binary-tree/',
        'https://leetcode.com/problems/validate-binary-search-tree/',
        'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
        'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',
    ],
    'graphs': [
        'https://leetcode.com/problems/number-of-islands/',
        'https://leetcode.com/problems/clone-graph/',
        'https://leetcode.com/problems/max-area-of-island/',
        'https://leetcode.com/problems/pacific-atlantic-water-flow/',
        'https://leetcode.com/problems/surrounded-regions/',
        'https://leetcode.com/problems/rotting-oranges/',
        'https://leetcode.com/problems/course-schedule/',
        'https://leetcode.com/problems/course-schedule-ii/',
        'https://leetcode.com/problems/redundant-connection/',
    ],
    'intervals': [
        'https://leetcode.com/problems/insert-interval/',
        'https://leetcode.com/problems/merge-intervals/',
        'https://leetcode.com/problems/non-overlapping-intervals/',
        'https://leetcode.com/problems/minimum-interval-to-include-each-query/'
    ]
}