OPERATORS = {
    'plus': '+',
    'minus': '-',
    'multiplied by': '*',
    'multiplied bi': '*',
    'multiply': '*',
    'divided by': '/',
    'divide': '/',
    'is equal to': '=',
    'equals to': '=',
    'equal to': '=',
    'equals': '=',
    'equal': '=',
    'is not equal to': '≠',
    'is not equal ': '≠',
    'not equal to': '≠',
    'greater than equal to': '≥',
    'less than equal to': '≤',
    'is greater than': '>',
    'greater than': '>',
    'is less than': '<',
    'less than': '<',
    'point': '.',
    'per cent': '%',
    'percent': '%',
    'square root of': '√'
}