
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-17T14:13:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f95fe5e1a66a11631e33bbe871384b773d8fa179",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
