from enum import Enum


class KomorebicEvent(Enum):
    ChangeLayout = "ChangeLayout"
    Cloak = "Cloak"
    CycleFocusMonitor = "CycleFocusMonitor"
    CycleFocusWorkspace = "CycleFocusWorkspace"
    EnsureWorkspaces = "EnsureWorkspaces"
    FocusChange = "FocusChange"
    FocusMonitorNumber = "FocusMonitorNumber"
    FocusMonitorWorkspaceNumber = "FocusMonitorWorkspaceNumber"
    FocusNamedWorkspace = "FocusNamedWorkspace"
    FocusWorkspaceNumber = "FocusWorkspaceNumber"
    KomorebiConnect = "KomorebiConnect"
    KomorebiDisconnect = "KomorebiDisconnect"
    KomorebiUpdate = "KomorebiUpdate"
    Manage = "Manage"
    MoveContainerToMonitorNumber = "MoveContainerToMonitorNumber"
    MoveContainerToWorkspaceNumber = "MoveContainerToWorkspaceNumber"
    MoveWorkspaceToMonitorNumber = "MoveWorkspaceToMonitorNumber"
    NewWorkspace = "NewWorkspace"
    Query = "Query"
    ReloadConfiguration = "ReloadConfiguration"
    SendContainerToMonitorNumber = "SendContainerToMonitorNumber"
    SendContainerToWorkspaceNumber = "SendContainerToWorkspaceNumber"
    State = "State"
    ToggleMaximise = "ToggleMaximise"
    ToggleMonocle = "ToggleMonocle"
    TogglePause = "TogglePause"
    ToggleTiling = "ToggleTiling"
    Uncloak = "Uncloak"
    Unmanage = "Unmanage"
    WatchConfiguration = "WatchConfiguration"
    WorkspaceName = "WorkspaceName"
