# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: path.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import apropos.goldmine.searchlight_protobuf_api.score_pb2 as score__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="path.proto",
    package="flowapi",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\npath.proto\x12\x07\x66lowapi\x1a\x0bscore.proto"2\n\tIPAddress\x12\x0c\n\x02v4\x18\x01 \x01(\tH\x00\x12\x0c\n\x02v6\x18\x02 \x01(\tH\x00\x42\t\n\x07\x61\x64\x64ress"\x8d\x01\n\x0bHopProperty\x12\x1d\n\x13max_bandwidth_bytes\x18\x01 \x01(\x03H\x00\x12\x1e\n\x14\x61\x64\x64\x65\x64_latency_millis\x18\x02 \x01(\x02H\x00\x12\x19\n\x0fphysical_device\x18\x03 \x01(\tH\x00\x12\x18\n\x0einterface_name\x18\x04 \x01(\tH\x00\x42\n\n\x08property"f\n\x03Hop\x12\x0c\n\x02id\x18\x01 \x01(\tH\x00\x12\x1e\n\x02ip\x18\x02 \x01(\x0b\x32\x12.flowapi.IPAddress\x12(\n\nproperties\x18\x03 \x03(\x0b\x32\x14.flowapi.HopPropertyB\x07\n\x05hopid"\xd0\x01\n\x07SubPath\x12\x0c\n\x02id\x18\x03 \x01(\tH\x00\x12\x39\n\x13\x61lternate_sub_paths\x18\x04 \x03(\x0b\x32\x1c.flowapi.SubPath.HopSequence\x1ao\n\x0bHopSequence\x12\x0c\n\x02id\x18\x01 \x01(\tH\x00\x12\x1a\n\x04hops\x18\x02 \x03(\x0b\x32\x0c.flowapi.Hop\x12\x1f\n\x05score\x18\x03 \x01(\x0b\x32\x0e.flowapi.ScoreH\x01\x42\x0c\n\nsequenceidB\x07\n\x05shareB\x0b\n\tsubpathid"C\n\x04Path\x12\x0c\n\x02id\x18\x01 \x01(\tH\x00\x12#\n\tsub_paths\x18\x02 \x03(\x0b\x32\x10.flowapi.SubPathB\x08\n\x06pathidb\x06proto3',
    dependencies=[
        score__pb2.DESCRIPTOR,
    ],
)


_IPADDRESS = _descriptor.Descriptor(
    name="IPAddress",
    full_name="flowapi.IPAddress",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="v4",
            full_name="flowapi.IPAddress.v4",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="v6",
            full_name="flowapi.IPAddress.v6",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="address",
            full_name="flowapi.IPAddress.address",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=36,
    serialized_end=86,
)


_HOPPROPERTY = _descriptor.Descriptor(
    name="HopProperty",
    full_name="flowapi.HopProperty",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="max_bandwidth_bytes",
            full_name="flowapi.HopProperty.max_bandwidth_bytes",
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="added_latency_millis",
            full_name="flowapi.HopProperty.added_latency_millis",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="physical_device",
            full_name="flowapi.HopProperty.physical_device",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="interface_name",
            full_name="flowapi.HopProperty.interface_name",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="property",
            full_name="flowapi.HopProperty.property",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=89,
    serialized_end=230,
)


_HOP = _descriptor.Descriptor(
    name="Hop",
    full_name="flowapi.Hop",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="flowapi.Hop.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="ip",
            full_name="flowapi.Hop.ip",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="properties",
            full_name="flowapi.Hop.properties",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="hopid",
            full_name="flowapi.Hop.hopid",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=232,
    serialized_end=334,
)


_SUBPATH_HOPSEQUENCE = _descriptor.Descriptor(
    name="HopSequence",
    full_name="flowapi.SubPath.HopSequence",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="flowapi.SubPath.HopSequence.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="hops",
            full_name="flowapi.SubPath.HopSequence.hops",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="score",
            full_name="flowapi.SubPath.HopSequence.score",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="sequenceid",
            full_name="flowapi.SubPath.HopSequence.sequenceid",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
        _descriptor.OneofDescriptor(
            name="share",
            full_name="flowapi.SubPath.HopSequence.share",
            index=1,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=421,
    serialized_end=532,
)

_SUBPATH = _descriptor.Descriptor(
    name="SubPath",
    full_name="flowapi.SubPath",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="flowapi.SubPath.id",
            index=0,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="alternate_sub_paths",
            full_name="flowapi.SubPath.alternate_sub_paths",
            index=1,
            number=4,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[
        _SUBPATH_HOPSEQUENCE,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="subpathid",
            full_name="flowapi.SubPath.subpathid",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=337,
    serialized_end=545,
)


_PATH = _descriptor.Descriptor(
    name="Path",
    full_name="flowapi.Path",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="flowapi.Path.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="sub_paths",
            full_name="flowapi.Path.sub_paths",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="pathid",
            full_name="flowapi.Path.pathid",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=547,
    serialized_end=614,
)

_IPADDRESS.oneofs_by_name["address"].fields.append(_IPADDRESS.fields_by_name["v4"])
_IPADDRESS.fields_by_name["v4"].containing_oneof = _IPADDRESS.oneofs_by_name["address"]
_IPADDRESS.oneofs_by_name["address"].fields.append(_IPADDRESS.fields_by_name["v6"])
_IPADDRESS.fields_by_name["v6"].containing_oneof = _IPADDRESS.oneofs_by_name["address"]
_HOPPROPERTY.oneofs_by_name["property"].fields.append(
    _HOPPROPERTY.fields_by_name["max_bandwidth_bytes"]
)
_HOPPROPERTY.fields_by_name[
    "max_bandwidth_bytes"
].containing_oneof = _HOPPROPERTY.oneofs_by_name["property"]
_HOPPROPERTY.oneofs_by_name["property"].fields.append(
    _HOPPROPERTY.fields_by_name["added_latency_millis"]
)
_HOPPROPERTY.fields_by_name[
    "added_latency_millis"
].containing_oneof = _HOPPROPERTY.oneofs_by_name["property"]
_HOPPROPERTY.oneofs_by_name["property"].fields.append(
    _HOPPROPERTY.fields_by_name["physical_device"]
)
_HOPPROPERTY.fields_by_name[
    "physical_device"
].containing_oneof = _HOPPROPERTY.oneofs_by_name["property"]
_HOPPROPERTY.oneofs_by_name["property"].fields.append(
    _HOPPROPERTY.fields_by_name["interface_name"]
)
_HOPPROPERTY.fields_by_name[
    "interface_name"
].containing_oneof = _HOPPROPERTY.oneofs_by_name["property"]
_HOP.fields_by_name["ip"].message_type = _IPADDRESS
_HOP.fields_by_name["properties"].message_type = _HOPPROPERTY
_HOP.oneofs_by_name["hopid"].fields.append(_HOP.fields_by_name["id"])
_HOP.fields_by_name["id"].containing_oneof = _HOP.oneofs_by_name["hopid"]
_SUBPATH_HOPSEQUENCE.fields_by_name["hops"].message_type = _HOP
_SUBPATH_HOPSEQUENCE.fields_by_name["score"].message_type = score__pb2._SCORE
_SUBPATH_HOPSEQUENCE.containing_type = _SUBPATH
_SUBPATH_HOPSEQUENCE.oneofs_by_name["sequenceid"].fields.append(
    _SUBPATH_HOPSEQUENCE.fields_by_name["id"]
)
_SUBPATH_HOPSEQUENCE.fields_by_name[
    "id"
].containing_oneof = _SUBPATH_HOPSEQUENCE.oneofs_by_name["sequenceid"]
_SUBPATH_HOPSEQUENCE.oneofs_by_name["share"].fields.append(
    _SUBPATH_HOPSEQUENCE.fields_by_name["score"]
)
_SUBPATH_HOPSEQUENCE.fields_by_name[
    "score"
].containing_oneof = _SUBPATH_HOPSEQUENCE.oneofs_by_name["share"]
_SUBPATH.fields_by_name["alternate_sub_paths"].message_type = _SUBPATH_HOPSEQUENCE
_SUBPATH.oneofs_by_name["subpathid"].fields.append(_SUBPATH.fields_by_name["id"])
_SUBPATH.fields_by_name["id"].containing_oneof = _SUBPATH.oneofs_by_name["subpathid"]
_PATH.fields_by_name["sub_paths"].message_type = _SUBPATH
_PATH.oneofs_by_name["pathid"].fields.append(_PATH.fields_by_name["id"])
_PATH.fields_by_name["id"].containing_oneof = _PATH.oneofs_by_name["pathid"]
DESCRIPTOR.message_types_by_name["IPAddress"] = _IPADDRESS
DESCRIPTOR.message_types_by_name["HopProperty"] = _HOPPROPERTY
DESCRIPTOR.message_types_by_name["Hop"] = _HOP
DESCRIPTOR.message_types_by_name["SubPath"] = _SUBPATH
DESCRIPTOR.message_types_by_name["Path"] = _PATH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IPAddress = _reflection.GeneratedProtocolMessageType(
    "IPAddress",
    (_message.Message,),
    {
        "DESCRIPTOR": _IPADDRESS,
        "__module__": "path_pb2"
        # @@protoc_insertion_point(class_scope:flowapi.IPAddress)
    },
)
_sym_db.RegisterMessage(IPAddress)

HopProperty = _reflection.GeneratedProtocolMessageType(
    "HopProperty",
    (_message.Message,),
    {
        "DESCRIPTOR": _HOPPROPERTY,
        "__module__": "path_pb2"
        # @@protoc_insertion_point(class_scope:flowapi.HopProperty)
    },
)
_sym_db.RegisterMessage(HopProperty)

Hop = _reflection.GeneratedProtocolMessageType(
    "Hop",
    (_message.Message,),
    {
        "DESCRIPTOR": _HOP,
        "__module__": "path_pb2"
        # @@protoc_insertion_point(class_scope:flowapi.Hop)
    },
)
_sym_db.RegisterMessage(Hop)

SubPath = _reflection.GeneratedProtocolMessageType(
    "SubPath",
    (_message.Message,),
    {
        "HopSequence": _reflection.GeneratedProtocolMessageType(
            "HopSequence",
            (_message.Message,),
            {
                "DESCRIPTOR": _SUBPATH_HOPSEQUENCE,
                "__module__": "path_pb2"
                # @@protoc_insertion_point(class_scope:flowapi.SubPath.HopSequence)
            },
        ),
        "DESCRIPTOR": _SUBPATH,
        "__module__": "path_pb2"
        # @@protoc_insertion_point(class_scope:flowapi.SubPath)
    },
)
_sym_db.RegisterMessage(SubPath)
_sym_db.RegisterMessage(SubPath.HopSequence)

Path = _reflection.GeneratedProtocolMessageType(
    "Path",
    (_message.Message,),
    {
        "DESCRIPTOR": _PATH,
        "__module__": "path_pb2"
        # @@protoc_insertion_point(class_scope:flowapi.Path)
    },
)
_sym_db.RegisterMessage(Path)


# @@protoc_insertion_point(module_scope)
