get_1d_att = {
    'data_date_A': 'A股最近交易日',
    'HGTN_notrade_date':'港深沪通北上资金在A股正常交易期间的停止交易日',
    'HGTS_notrade_date':'港深沪通南向资金在A股正常交易期间的停止交易日',
    'stocklisting_A':'沪深京上市挂牌交易A股集合,不含已退市股票',
    'stocklisting_SHSZ':'沪深上市挂牌交易A股集合,不含京交所股票,不含已退市股票',
    'stocklist_A':'沪深京上市挂牌交易A股集合,,含已退市股票',
    'ETF_CN_bond':'中国内地市场债券类ETF',
    'ETF_CN_com':'中国内地市场商品类ETF',
    'ETF_CN_QDII':'中国内地市场QDII类ETF',
    'ETF_CN_stock':'中国内地市场股票类ETF',    
    'ETF_CN':'中国内地市场ETF，不含已退市品种',
    'ETF_CN_all':'中国内地市场ETF，含已退市品种',
    'MSS_Stock_A': 'A股目前融资融券标的股票代码列表',
    'MSS_ETF_A':'A股目前融资融券标的ETF代码列表',
    'td_new_ETF_CN':'最近交易日新上市ETF',
     'ZZi':'中证指数合集',
     'BJA': '京交所目前挂牌交易股票代码列表(不含退市/未上市股)',
     'CSi': '中证指数代码列表',
     'ETF_CN': '沪深两市挂牌交易ETF代码列表',
     'GZi': '国证指数代码列表',
     'HGT_A': 'A股目前沪港通股票代码列表',
     'index_CN': '两市挂牌指数合集',
     'SME_SZA': '深交所创业中小板挂牌交易股票代码列表(不含退市/未上市股)',
     'SCI_SHA': '上交所科创板目前挂牌交易股票代码列表(不含退市/未上市股)',
     'SHA': '上交所目前挂牌交易股票代码列表(不含退市/未上市股)',
     'SHi': '上交所挂牌指数列表',
     'SZA': '深交所目前挂牌交易股票代码列表(不含退市/未上市股)',
     'SZi': '深交所挂牌指数列表',
     'c2sn_A': 'A股证券代码 ->简称字典',
     'sn2c_A': 'A股证券简称 -> 代码字典',
     'c2sn_CNi':'A股指数代码 ->简称字典',
     'sn2c_CNi':'A股指数简称 -> 代码字典',
     'delisted_A': 'A股已退市股票代码列表',
     'delisting_A': 'A股已暂停上市股票代码列',
     'pre_IPO_A': 'A股目前已过审等候上市股票代码列表',
     'removed_ETF_CN': '沪深两市已摘牌ETF代码列表',
     'stock_A_bus_sector': 'A股最近交易日行业->股票代码合集字典',
     'stock_A_concept': 'A股最近交易日概念->股票代码合集字典',
     'stock_A_ipodate': 'A股代码 -> IPO日期字典',
     'stock_A_region': 'A股最近交易日区域->股票代码合集字典',
     'stocklist_B': '沪深两市B股代码列表(含退市/未上市股)',
     'stocklisting_B': '沪深两市挂牌交易B股代码列表(不含退市/未上市股)',
     'susp_ETF_CN': '沪深两市最近交易日停牌ETF代码列表',
     'suspended_A': 'A股最近交易日停牌股票代码列表',
     'td_IPO_A': 'A股最近交易日IPO股票代码列表',
     'td_delisted_A': 'A股最近交易日摘牌股票代码列表',
     'with_anno_A': 'A股最近交易日有停牌公告股票代码列表',
     'IPO_date_A': 'A股股票(含退市)IPO日合集字典',
     'delisted_date_A':'A股退市股退市日合集字典',
     'ST_stock_A':'A股st股合集',
     'SST_stock_A':'A股退市警示板股合集',
     'CB_CN_all':'A股可转债合集(含退市)',
     'c2sn_CBCN':'A股可转债代码->简称字典',
     'sn2c_CBCN':'A股可转债简称->代码字典',
     'CB_CN_prelist':'A股待上市可转债代码合集',
     'CB_CN_delisted':'A股已退市可转债代码合集',
     'CB_CN':'A股在挂牌交易可转债合集',
     'td_new_CB_CN':'A股今日上市可转债合集',
     'ETFO_CN':'两市目前挂牌ETF期权合集',
     'c2sn_ETFO_CN':'两市挂牌ETF期权代码->简称字典',
     'sn2c_ETFO_CN':'两市挂牌ETF期权简称->代码字典',
     }

get_tick_att = {'last_I':'最新成交价',
                'volume_I':'截止上一个跳价时段成交量(单位手)',
                'dir_I':'跳价方向; 0,1,-1 分别为中性，买入，卖出交易',
                'amt_I':'截止上一个跳价时段成交额(单位千)'}

get_hf5_att = { 'open_I':'当日开盘价',
                'pre_close_I':'上个交易日收盘价',
                'last_I':'最新成交价',
                'high_I':'日间最高价',
                'low_I':'日间最低价',
                'volume_I':'累计成交量，单位为手',
                'amt_I':'累计成交额,单位千',
                'bidx':'x档买入价',
                'askx':'x档卖出价',
                'bsizex':'x档买入量,单位手',
                'asizex':'x档卖出量,单位手'
               }

get_daily_name= {
    "daily":{
             'open': '开盘价', 
             'high': '最高价', 
             'low': '最低价', 
             'close': '收盘价', 
             'change': '昨日变化(复权)', 
             'pct_chg': '百分比变化(单位%)',
             'pre_close': '昨收价(复权)',
             'vol': '成交量(手)', 
             'amount': '成交额(千)',
             #'pindex':'收益指数(上市日初始单位为1，分红再投资收益)'
            },
    "valuation":{
              "pb":"市净率",
              "pb_tpar":"市净率(归母权益)",
              "pe":"市盈率",
              'pe_ttm':"市盈率_TTM",
              'pe_kf':"市盈率_扣除损益",
              'pe_kf_ttm':"市盈率_扣除损益_TTM",
              'pe_tpar':"市盈率_母公司",
              "pe_tpar_ttm":"市盈率_母公司TTM",
              "ps":"市销率",
              'ps_ttm':"市销率_TTM",
              'pcf':"市现率",
               "pcf_ttm":"市现率_TTM",
               'ptb':"市值有形资产比",
               "ctb_ttm":"现金流市值比_TTM",
               "mvtebit_ttm":"总市值/税前净利润_TTM",
               "peg_ttm":"市盈增长比率_TTM",
               "prange":"股票日振幅",	
               "turnover":"换手率",
               "beta_hs300_1m":"beta沪深300近一月",	
               "beta_hs300_3m":"beta沪深300近三月",	
               "beta_hs300_6m":"beta沪深300近六月",	
               "beta_zz500_1m":"beta中证500近一月",	
               "beta_zz500_3m":"beta中证500近三月",	
               "beta_zz500_6m":"beta中证500近六月",	
              },
    
    
    
    
        "ms": {'mg_amt': '融资买入总额,单位千', 
               'mg_bal_amt': '融资余额,单位千', 
               'mg_repay_amt': '融资偿还额,单位千', 
               'ss_bal_amt': '融券余额,单位千', 
               'ss_bal_share': '融券余量,单位手', 
               'ss_repay_share':'融券偿还量,单位手', 
               'ss_vol_share':'融券卖出量,单位手',
               "ms_bal":"融资融券余额"
                 }
              }



get_HSGT_name = {"summary_S":{
                     "SH2HK_nb_order":"港股通沪买单量(挂单+成交)",
                     "SH2HK_nb_amt":"港股通沪成交量",           
                     "SH2HK_bal":"港股通沪余额(挂单+成交)",                
                     "SH2HK_acc_nb_amt":"港股通沪累计净买成交量",         
                     "SH2HK_bamt":"港股通沪买入量",             
                     "SH2HK_samt":"港股通沪卖出量",               
                     "SZ2HK_nb_order":"港股通深买单量(挂单+成交)",     
                     "SZ2HK_nb_amt":"港股通深成交量",            
                     "SZ2HK_bal":"港股通深余额(挂单+成交)",          
                     "SZ2HK_acc_nb_amt":"港股通深累计净买成交量",         
                     "SZ2HK_bamt":"港股通深买入量",                   
                     "SZ2HK_samt":"港股通深卖出量",                     
                          },
                  "summary_N":
                       {
                           "HK2SH_nb_order":"沪港通买单量(挂单+成交)",
                           "HK2SH_nb_amt":"沪港通成交量",           
                           "HK2SH_bal":"沪港股通沪余额(挂单+成交)",                
                           "HK2SH_acc_nb_amt":"港股通沪累计净买成交量",         
                           "HK2SH_bamt":"港股通沪买入量",             
                           "HK2SH_samt":"港股通沪卖出量",               
                           "HK2SZ_nb_order":"港股通深买单量(挂单+成交)",     
                           "HK2SZ_nb_amt":"港股通深成交量",            
                           "HK2SZ_bal":"港股通深余额(挂单+成交)",          
                           "HK2SZ_acc_nb_amt":"港股通深累计净买成交量",         
                           "HK2SZ_bamt":"港股通深买入量",                   
                           "HK2SZ_samt":"港股通深卖出量",        
                           "HGTN_mv":"北向持仓总市值",
                           "HGTN_mv_pct2allmv":"北向持仓占A股总市值百分比",
                           "HGTN_mv_chg":"北向总市值百分比变化",
                           "HGTN_mv_chg_pct2allmv":"北向市值变化对A股总市值百分比"
                           },
               
                    }


get_econ_name = {"Shibor":
                 {
                 "1Y":'一年期银行间同业拆放利率每日历史报价,单位%',
                 "9M":'9月期银行间同业拆放利率每日历史报价,单位%',
                 "6M":'6月期银行间同业拆放利率每日历史报价,单位%',
                 "3M":'3月期银行间同业拆放利率每日历史报价,单位%',
                 "1M":'1月期银行间同业拆放利率每日历史报价,单位%',
                 "2W":'14日银行间同业拆放利率每日历史报价,单位%',
                 "1W":'7日银行间同业拆放利率每日历史报价,单位%',
                 "ON":'隔夜银行间同业拆放利率每日历史报价,单位%',
                 }
                     }




get_stock_fs_name = {"balance":{
                                "cash_equi":"货币资金,现金,存放中央银行款项",
                                "sett_fund":"金融类公司结算备付金",
                                "lend_fund":"金融类公司拆出资金",
                                "fin_assets":"以公允价值计量且变动计入当期损益的金融资产",
                                "note_rbl":"应收票据",
                                "div_rbl":"应收分红",
                                "int_rbl":"应收利息",
                                "acc_rbl":"应收账款",
                                "oher_rbl":"其他应收款",
                                "prepay":"预付款项",
                                "invents":"存货",
                                "nc_ats":"一年内到期的非流动资产",
                                "other_cats":"其他流动资产",
                                "total_cats":"流动资产合计",
                                "loan_ads":"金融公司发放贷款和垫款",
                                "salb_fa":"可供出售金融资产",
                                "htm_ats":"持有至到期投资",
                                "estate_asts":"投资性房地产",
                                "lt_equity":"长期股权投资",
                                "lt_re":"长期应收款",
                                "fixed_assets":"固定资产",
                                "con_mals":"工程物资",
                                "const_ip":"在建工程",
                                "fia_disp":"固定资产清理",
                                "bio_asts":"生产性生物资产",
                                "oa_asts":"油气资产",
                                "intangibles":"无形资产",
                                "dev_expens":"开发支出",
                                "goodwill":"商誉",
                                "lt_prepaids":"长期待摊费用",
                                "def_taxes":"递延所得税资产",
                                "other_nca":"其他非流动资产",
                                "total_nca":"非流动资产合计",
                                "total_assets":"资产总计",
                                "st_lia":"短期借款",
                                "cb_lia":"金融公司向中央银行借款",
                                "fin_depo":"同业及其他金融机构存放款项",
                                "note_pbl":"应付票据",
                                "acc_pbl":"应付账款",
                                "adv_pbl":"预收款项",
                                "sal_pbl":"应付职工薪酬",
                                "div_pbl":"应付股利",
                                "tax_pbl":"应交税费",
                                "int_pbl":"应付利息",
                                "other_pbl":"其他应付款",
                                "nclia":"一年内到期的非流动负债",
                                "other_clia":"其他流动负债",
                                "total_clia":"流动负债合计",
                                "lt_borl":"长期借款",
                                "bond_pbl":"应付债券",
                                "lt_pbl":"长期应付款",
                                "sp_pbl":"专项应付款",
                                "exp_pbl":"预计负债",
                                "deftax_pbl":"递延所得税负债",
                                "other_nclia":"其他非流动负债",
                                "total_nclia":"非流动负债合计",
                                "total_lia":"负债合计",
                                "pd_cap":"实收资本股本",
                                "cap_reser":"资本公积",
                                "treasury_stock":"库存股",
                                "sp_reser":"专项储备",
                                "sur_reser":"盈余公积",
                                "ret_profit":"未分配利润",
                                "risk_reser":"一般风险准备",
                                "forex_cov_diff":"外币报表折算差额",
                                "ri_to_parent":"归属母公司权益合计",
                                "ri_to_minor":"少数股东权益",
                                "shareholder_equity":"所有者权益合计",
                                "total_lia_equity":"负债和所有者权益合计",
                                "anno_date":"财报公开日"
                                },
                'income':{
                    "opic":"营业收入",
                    "intncom":"金融类公司利息净收入",
                    "com_net":"金融类公司手续费及佣金净收入",
                    "opic_nofin":"非金类营业总收入",
                    "op_costnf": "非金类营业总成本",
                    "op_cost": "非金类营业成本",
                    "op_tax_cost":"营业税金及附加",
                    "sale_exp":"非金类销售费用",
                    "man_exp": "非金类管理费用",
                    "fin_exp":"非金类财务费用",
                    "asset_depre":"资产减值损失",
                    "fv_chg": "公允价值变动净收益",
                    "inv_ic": "投资收益",
                    "exc_inc":"汇兑收益",
                    "op_profit":"营业利润",
                    "non_op_inc":"营业利润:营业外收入",
                    "non_op_exp":"营业利润:营业外支出",
                    "total_profit": "利润总额",
                    "income_tax":"利润总额减：所得税费用",
                    "net_profit":"净利润",
                    "np_parent":"归属于母公司所有者的净利润",
                    "np_minor": "少数股东损益",
                    "other_ic":"其他综合收益",
                    "other_icntax_parent": "归属于母公司所有者的其他综合收益的税后净额",
                    "total_compre_inc": "综合收益总额",
                    "total_compre_inc_parent":"归属于母公司所有者的综合收益总额",
                    "anno_date":"财报公开日"
                    },
                "cashflow": {
                    "gs_rec":"非金类销售商品、提供劳务收到的现金",
                    "net_depo_rec":"非金类客户存款和同业存放款项净增加额",
                    "intcom_rec":"(金融类)收取利息、手续费及佣金的现金",
                    "other_op_rec": "收到其他与经营活动有关的现金",
                    "op_rec": "经营活动现金流入合计",
                    "gs_paid": "非金类购买商品、接受劳务支付的现金",
                    "sal_paid": "支付给职工以及为职工支付的现金",
                    "taxes_paid":  "支付的各项税费",
                    "intcom_paid": "(金融类)支付利息、手续费及佣金的现金",
                    "other_op_paid":"支付其他与经营活动有关的现金",
                    "op_net":"经营活动现金流量净额",
                    "invest_rec":"收回投资收到的现金",
                    "rint_rec":"取得投资收益收到的现金",
                    "depas_net":"处置固定资产、无形资产和其他长期资产收回净额",
                    "subdepas_net":"处置子公司及其他营业单位收到净额",
                    "invact_rec":"投资活动现金流入合计",
                    "invlt_paid":"购建固定资产、无形资产和其他长期资产支付现金",
                    "invt_paid":"投资支付现金",
                    "acqsub_paid":"取得子公司及其他营业单位支付的现金净额",
                    "other_inv_paid":"支付其他与投资活动有关的现金",
                    "inv_paid":"投资活动现金流出合计",
                    "inv_net":"投资活动现金流量净额",
                    "rinvt_rec":"吸收投资收到的现金",
                    "bondis_rec":"发行债券收到的现金",
                    "bor_rec":"取得借款收到的现金",
                    "other_fin_rec":"收到其他与筹资活动有关的现金",
                    "fin_rec":"筹资活动现金流入合计",
                    "debt_paid":"偿还债务支付的现金",
                    "intdiv_paid":"分配股利、利润或偿付利息支付的现金",
                    "other_fin_piad":"支付其他与筹资活动有关的现金",
                    "fin_paid":"筹资活动现金流出合计",
                    "fin_net":"筹资活动现金流量净额",
                    "exc_chg":"汇率变动对现金及现金等价物的影响",
                    "cash_net":"现金及等价物净增加额",
                    "cash_start":"期初现金及现金等价物余额",
                    "anno_date":"财报公开日"
                        }}

get_hist_share_att = {
    "total_share":"总股本(单位:股）",	
    "restricted_share":"受限流通股合计",	
    "float_share":"流通股本",	
    "listed_float_share":"上市流通股本",	
    "description":"变动说明",	
                }


#beta
"""
get_daily_pro_att = { 
           'stock_A': 
             {
             'open': '开盘价', 
             'high': '最高价', 
             'low': '最低价', 
             'close': '收盘价', 
             'change': '昨日变化', 
             'pct_chg': '百分比变化(单位%)',  
             'vol': '成交量(手)', 
             'amount': '成交额(千)',
             'ST': '日线ST股标签，0否，1是',
             'pre_close': '昨收价(自动除权)', 
             'ave_price': '日内成交额加权均价', 
             'total_mv': '总市值(含非A股，单位:千)', 
             'total_share': '总股本(含非A股，单位:手)',      
             'circ_mv': '流通A股市值(千)',              
             'volume_ratio': '量比，即当日成交量/过去5日均值，单位%',
             'turnover': '换手率(%)', 
             'pindex': '收益指数(上市日初始单位为1，分红再投资收益)',              
             'float_share': '流通A股(手)', 
             'maxupordown': '日线涨停板标签，0否，1涨停，2跌停', 
             'susp_days': '日线计划持续停牌日', 
             'susp_reason': '日线停盘原因', 
             'trade_status': '日线交易状态', 
             'uplimit': '日线涨停价',            
             'downlimit': '日线跌停价', 
             'open_amount': '开盘集合竞价成交额，单位千', 
             'close_amount': '收盘竞价成交额，单位千',               
             'mf_in': '流入额，即日内总买入成交额，单位千', 
             'mf_out': '流出额，即日内总卖出成交额，单位千', 
             'l_bamt': '买方主动大单成交额, 大单-单笔规模100万+,单位千', 
             'l_samt': '卖方主动大单成交额, 大单-单笔规模100万+,单位千', 
             'l_mf_in': '大单流入额,大单-单笔规模100万+,单位千', 
             'l_mf_out': '大单流出额,大单-单笔规模100万+,单位千', 
             'm_bamt': '买方主动中单成交额,中单-单笔规模20-100万之间,单位千', 
             'm_samt': '卖方主动中单成交额,中单-单笔规模20-100万之间,单位千',
             'm_mf_in': '中单流入额,中单-单笔规模20-100万之间,单位千',
             'm_mf_out': '中单流出额,中单-单笔规模20-100万之间,单位千', 
             's_bamt': '买方主动小单成交额,小单-单笔规模5万-,单位千', 
             's_samt': '卖方主动小单成交额,小单-单笔规模5万-,单位千',
             's_mf_in': '小单流入额,小单-单笔规模5万-,单位千', 
             's_mf_out': '小单流出额,小单-单笔规模5万-,单位千', 
               },
             
      'ETF_CN': 
             {'IOPV': '收盘时参考单位净值',
              'amount': '成交额(千)', 
              'ave_price': '日内成交额加权均价', 
              'ba_spread': '收盘买卖差价', 
              'change': '昨日变化', 
              'close_amount': '收盘竞价成交额，单位千', 
              'cnav': '累计单位净值', 
              'open': '开盘价', 
              'high': '最高价', 
              'low': '最低价',
              'close': '收盘价',   
              'l_bamt': '买方大单成交额, 大单-单笔规模100万+,单位千', 
              'l_mf_in': '大单流入额,大单-单笔规模100万+,单位千', 
              'l_mf_out': '大单流出额,大单-单笔规模100万+,单位千', 
              'l_samt': '卖方大单成交额, 大单-单笔规模100万+,单位千', 
              'm_bamt': '买方中单成交额,中单-单笔规模20-100万之间,单位千', 
              'm_mf_in': '中单流入额,中单-单笔规模20-100万之间,单位千', 
              'm_mf_out': '中单流出额,中单-单笔规模20-100万之间,单位千', 
              'm_samt': '卖方中单成交额,中单-单笔规模20-100万之间,单位千', 
              'mf_in': '流入额，即日内总买入成交额，单位千', 
              'mf_out': '流出额，即日内总卖出成交额，单位千', 
              'nav': '单位净值', 
              'nav_pct_chg': '净值增长率,分红/扩股自动调整, 单位%', 
              'open_amount': '开盘集合竞价成交额，单位千', 
              'pct_chg': '百分比变化(单位%)',
              'pindex': '收益指数(上市日初始单位为1，分红再投资收益)', 
              'pn_rate': '溢价率,即市价/单位净值, 分红/扩股自动调整, 单位%', 
              'pre_close': '昨收价(自动除权)', 
              's_bamt': '买方小单成交额,小单-单笔规模20万-,单位千', 
              's_mf_in': '小单流入额,小单-单笔规模20万-,单位千', 
              's_mf_out': '小单流出额,小单-单笔规模20万-,单位千', 
              's_samt': '卖方小单成交额,小单-单笔规模20万-,单位千', 

              'total_share': '总单位份额, 见每日交易所公告', 
              'trade_status': '日线交易状态', 
              'turnover': '换手率(%)', 
              'vol': '成交量(手)', 
              'volume_ratio': '量比，即当日成交量/过去5日均值，单位%'
              },
             
      'ETFO_CN': 
             {
             'pre_close': '昨收价(自动除权)', 
             'open': '开盘价', 
             'high': '最高价', 
             'low': '最低价', 
             'close': '收盘价', 
             'ave_price': '日内成交额加权均价', 
             'change': '昨日变化', 
             'pct_chg': '百分比变化(单位%)',    
             'pre_settle':'前结算价',
             'amount': '成交额(千)', 
             'open_pos': '持仓',      
             'settle_price': '结算价',              
             'vol': '成交量(手)',              
             'open_amount': '开盘集合竞价成交额，单位千', 
             'close_amount': '收盘竞价成交额，单位千',  
             'duration':'剩余期限(天)',
             'mf_in': '流入额，即日内总买入成交额，单位千', 
             'mf_out': '流出额，即日内总卖出成交额，单位千',            
             'open_amount': '开盘集合竞价成交额，单位千', 
             'close_amount': '收盘竞价成交额，单位千',    
             'int_value':'内在价值',
             'delta':'衡量标的资产价格变动时,期权价格的变化幅度',
             'gamma':'表示Delta值对于标的物价格变动的敏感程度',
             'vega':'隐含波动率的敏感度',
             'theta':'时间变化对期权理论价值的影响',
             'rho':'利率转变对期权价值影响',
             'implied_vol':'隐含波动率',
             'expected_value':'理论价',
             'pn_rate':'溢价率',
              },

      'index_CN':
             {
              'open': '开盘价', 
              'high': '最高价', 
              'low': '最低价', 
              'close': '收盘价', 
              'change': '昨日变化', 
              'pct_chg': '百分比变化(单位%)',      
              'amount': '成交额(千)',  
              'vol': '成交量(手)',    
                 },

      'CB_CN': 
             {
             'pre_close': '昨收价(自动除权)', 
             'open': '开盘价', 
             'high': '最高价', 
             'low': '最低价', 
             'close': '收盘价', 
             'ave_price': '日内成交额加权均价', 
             'change': '昨日变化', 
             'pct_chg': '百分比变化(单位%)',      
             'amount': '成交额(千)', 
             'vol': '成交量(手,10张)', 
             'volume_ratio': '量比，即当日成交量/过去5日均值，单位%',
             'ba_spread': '最近报价最优买卖差', 
             'mf_in': '流入额，即日内总买入成交额，单位千', 
             'mf_out': '流出额，即日内总卖出成交额，单位千',            
             'open_amount': '开盘集合竞价成交额，单位千', 
             'close_amount': '收盘竞价成交额，单位千',  
             'bond_value':'纯债价',
             'convert_value':'转股值',
             'pn_rate':'溢价率'
              }
    
             }
"""