
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-19T18:35:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef66f852072d217a7be4ccb26514c37d70c23114",
 "version": "2.0.3.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
