# Generated by Django 2.2.15 on 2021-01-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_play', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videosplay',
            options={'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
        migrations.AlterModelOptions(
            name='videosplaythrough',
            options={'verbose_name': '视频标签中间件', 'verbose_name_plural': '视频标签中间件'},
        ),
    ]
