# Generated by Django 3.1.5 on 2021-01-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_play', '0002_auto_20210103_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosplay',
            name='is_mark_file',
            field=models.BooleanField(default=False, verbose_name='标记文件'),
        ),
    ]
