# Generated by Django 3.1.5 on 2021-06-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_play', '0004_videosplay_vr_projection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosplay',
            name='is_ignore',
            field=models.BooleanField(default=False, help_text='收藏的文件，如果忽略也可以不备份', verbose_name='忽略'),
        ),
    ]
