# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sora.app.v1beta import service_pb2 as sora_dot_app_dot_v1beta_dot_service__pb2


class AppServiceStub(object):
    """Server <-> Application API
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamState = channel.unary_stream(
                '/sora.app.v1beta.AppService/StreamState',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.StreamStateRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.StreamStateResponse.FromString,
                )
        self.StreamEvents = channel.unary_stream(
                '/sora.app.v1beta.AppService/StreamEvents',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.StreamEventsResponse.FromString,
                )
        self.QueryState = channel.unary_unary(
                '/sora.app.v1beta.AppService/QueryState',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.QueryStateRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.QueryStateResponse.FromString,
                )
        self.QueryEvents = channel.unary_unary(
                '/sora.app.v1beta.AppService/QueryEvents',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.QueryEventsRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.QueryEventsResponse.FromString,
                )
        self.QueryStateAggregate = channel.unary_unary(
                '/sora.app.v1beta.AppService/QueryStateAggregate',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.QueryStateAggregateRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.QueryStateAggregateResponse.FromString,
                )
        self.ReadLayers = channel.unary_unary(
                '/sora.app.v1beta.AppService/ReadLayers',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadLayersRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadLayersResponse.FromString,
                )
        self.CreateLayer = channel.unary_unary(
                '/sora.app.v1beta.AppService/CreateLayer',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateLayerRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateLayerResponse.FromString,
                )
        self.UpdateLayer = channel.unary_unary(
                '/sora.app.v1beta.AppService/UpdateLayer',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateLayerRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateLayerResponse.FromString,
                )
        self.DeleteLayer = channel.unary_unary(
                '/sora.app.v1beta.AppService/DeleteLayer',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteLayerRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteLayerResponse.FromString,
                )
        self.ReadEventGenerators = channel.unary_unary(
                '/sora.app.v1beta.AppService/ReadEventGenerators',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadEventGeneratorsRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadEventGeneratorsResponse.FromString,
                )
        self.CreateEventGenerator = channel.unary_unary(
                '/sora.app.v1beta.AppService/CreateEventGenerator',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateEventGeneratorRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateEventGeneratorResponse.FromString,
                )
        self.UpdateEventGenerator = channel.unary_unary(
                '/sora.app.v1beta.AppService/UpdateEventGenerator',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateEventGeneratorRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateEventGeneratorResponse.FromString,
                )
        self.DeleteEventGenerator = channel.unary_unary(
                '/sora.app.v1beta.AppService/DeleteEventGenerator',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteEventGeneratorRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteEventGeneratorResponse.FromString,
                )
        self.ReadAlertors = channel.unary_unary(
                '/sora.app.v1beta.AppService/ReadAlertors',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadAlertorsRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadAlertorsResponse.FromString,
                )
        self.CreateAlertor = channel.unary_unary(
                '/sora.app.v1beta.AppService/CreateAlertor',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateAlertorRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateAlertorResponse.FromString,
                )
        self.UpdateAlertor = channel.unary_unary(
                '/sora.app.v1beta.AppService/UpdateAlertor',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateAlertorRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateAlertorResponse.FromString,
                )
        self.DeleteAlertor = channel.unary_unary(
                '/sora.app.v1beta.AppService/DeleteAlertor',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteAlertorRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteAlertorResponse.FromString,
                )
        self.ReadAnnotators = channel.unary_unary(
                '/sora.app.v1beta.AppService/ReadAnnotators',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadAnnotatorsRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadAnnotatorsResponse.FromString,
                )
        self.CreateAnnotator = channel.unary_unary(
                '/sora.app.v1beta.AppService/CreateAnnotator',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateAnnotatorRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateAnnotatorResponse.FromString,
                )
        self.UpdateAnnotator = channel.unary_unary(
                '/sora.app.v1beta.AppService/UpdateAnnotator',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateAnnotatorRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateAnnotatorResponse.FromString,
                )
        self.DeleteAnnotator = channel.unary_unary(
                '/sora.app.v1beta.AppService/DeleteAnnotator',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteAnnotatorRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteAnnotatorResponse.FromString,
                )
        self.ReadProjects = channel.unary_unary(
                '/sora.app.v1beta.AppService/ReadProjects',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadProjectsRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadProjectsResponse.FromString,
                )
        self.CreateProject = channel.unary_unary(
                '/sora.app.v1beta.AppService/CreateProject',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateProjectResponse.FromString,
                )
        self.UpdateProject = channel.unary_unary(
                '/sora.app.v1beta.AppService/UpdateProject',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateProjectRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateProjectResponse.FromString,
                )
        self.DeleteProject = channel.unary_unary(
                '/sora.app.v1beta.AppService/DeleteProject',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteProjectRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteProjectResponse.FromString,
                )
        self.ReadDevices = channel.unary_unary(
                '/sora.app.v1beta.AppService/ReadDevices',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadDevicesRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadDevicesResponse.FromString,
                )
        self.CreateDevice = channel.unary_unary(
                '/sora.app.v1beta.AppService/CreateDevice',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateDeviceRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateDeviceResponse.FromString,
                )
        self.UpdateDevice = channel.unary_unary(
                '/sora.app.v1beta.AppService/UpdateDevice',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateDeviceRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateDeviceResponse.FromString,
                )
        self.DeleteDevice = channel.unary_unary(
                '/sora.app.v1beta.AppService/DeleteDevice',
                request_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteDeviceRequest.SerializeToString,
                response_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteDeviceResponse.FromString,
                )


class AppServiceServicer(object):
    """Server <-> Application API
    """

    def StreamState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStateAggregate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadLayers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadEventGenerators(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEventGenerator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEventGenerator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEventGenerator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadAlertors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAlertor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAlertor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAlertor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadAnnotators(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAnnotator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAnnotator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAnnotator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.StreamStateRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.StreamStateResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.StreamEventsRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.StreamEventsResponse.SerializeToString,
            ),
            'QueryState': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryState,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.QueryStateRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.QueryStateResponse.SerializeToString,
            ),
            'QueryEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryEvents,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.QueryEventsRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.QueryEventsResponse.SerializeToString,
            ),
            'QueryStateAggregate': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryStateAggregate,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.QueryStateAggregateRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.QueryStateAggregateResponse.SerializeToString,
            ),
            'ReadLayers': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadLayers,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadLayersRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadLayersResponse.SerializeToString,
            ),
            'CreateLayer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLayer,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateLayerRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateLayerResponse.SerializeToString,
            ),
            'UpdateLayer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLayer,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateLayerRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateLayerResponse.SerializeToString,
            ),
            'DeleteLayer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLayer,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteLayerRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteLayerResponse.SerializeToString,
            ),
            'ReadEventGenerators': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadEventGenerators,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadEventGeneratorsRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadEventGeneratorsResponse.SerializeToString,
            ),
            'CreateEventGenerator': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEventGenerator,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateEventGeneratorRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateEventGeneratorResponse.SerializeToString,
            ),
            'UpdateEventGenerator': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEventGenerator,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateEventGeneratorRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateEventGeneratorResponse.SerializeToString,
            ),
            'DeleteEventGenerator': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEventGenerator,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteEventGeneratorRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteEventGeneratorResponse.SerializeToString,
            ),
            'ReadAlertors': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadAlertors,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadAlertorsRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadAlertorsResponse.SerializeToString,
            ),
            'CreateAlertor': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAlertor,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateAlertorRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateAlertorResponse.SerializeToString,
            ),
            'UpdateAlertor': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAlertor,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateAlertorRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateAlertorResponse.SerializeToString,
            ),
            'DeleteAlertor': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAlertor,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteAlertorRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteAlertorResponse.SerializeToString,
            ),
            'ReadAnnotators': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadAnnotators,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadAnnotatorsRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadAnnotatorsResponse.SerializeToString,
            ),
            'CreateAnnotator': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAnnotator,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateAnnotatorRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateAnnotatorResponse.SerializeToString,
            ),
            'UpdateAnnotator': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAnnotator,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateAnnotatorRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateAnnotatorResponse.SerializeToString,
            ),
            'DeleteAnnotator': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAnnotator,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteAnnotatorRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteAnnotatorResponse.SerializeToString,
            ),
            'ReadProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadProjects,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadProjectsRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadProjectsResponse.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateProjectRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateProjectResponse.SerializeToString,
            ),
            'UpdateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProject,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateProjectRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateProjectResponse.SerializeToString,
            ),
            'DeleteProject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProject,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteProjectRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteProjectResponse.SerializeToString,
            ),
            'ReadDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDevices,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadDevicesRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.ReadDevicesResponse.SerializeToString,
            ),
            'CreateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDevice,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateDeviceRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.CreateDeviceResponse.SerializeToString,
            ),
            'UpdateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDevice,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateDeviceRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.UpdateDeviceResponse.SerializeToString,
            ),
            'DeleteDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDevice,
                    request_deserializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteDeviceRequest.FromString,
                    response_serializer=sora_dot_app_dot_v1beta_dot_service__pb2.DeleteDeviceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sora.app.v1beta.AppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AppService(object):
    """Server <-> Application API
    """

    @staticmethod
    def StreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sora.app.v1beta.AppService/StreamState',
            sora_dot_app_dot_v1beta_dot_service__pb2.StreamStateRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.StreamStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sora.app.v1beta.AppService/StreamEvents',
            sora_dot_app_dot_v1beta_dot_service__pb2.StreamEventsRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.StreamEventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/QueryState',
            sora_dot_app_dot_v1beta_dot_service__pb2.QueryStateRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.QueryStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/QueryEvents',
            sora_dot_app_dot_v1beta_dot_service__pb2.QueryEventsRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.QueryEventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryStateAggregate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/QueryStateAggregate',
            sora_dot_app_dot_v1beta_dot_service__pb2.QueryStateAggregateRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.QueryStateAggregateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadLayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/ReadLayers',
            sora_dot_app_dot_v1beta_dot_service__pb2.ReadLayersRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.ReadLayersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateLayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/CreateLayer',
            sora_dot_app_dot_v1beta_dot_service__pb2.CreateLayerRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.CreateLayerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateLayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/UpdateLayer',
            sora_dot_app_dot_v1beta_dot_service__pb2.UpdateLayerRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.UpdateLayerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteLayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/DeleteLayer',
            sora_dot_app_dot_v1beta_dot_service__pb2.DeleteLayerRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.DeleteLayerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadEventGenerators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/ReadEventGenerators',
            sora_dot_app_dot_v1beta_dot_service__pb2.ReadEventGeneratorsRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.ReadEventGeneratorsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEventGenerator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/CreateEventGenerator',
            sora_dot_app_dot_v1beta_dot_service__pb2.CreateEventGeneratorRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.CreateEventGeneratorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateEventGenerator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/UpdateEventGenerator',
            sora_dot_app_dot_v1beta_dot_service__pb2.UpdateEventGeneratorRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.UpdateEventGeneratorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteEventGenerator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/DeleteEventGenerator',
            sora_dot_app_dot_v1beta_dot_service__pb2.DeleteEventGeneratorRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.DeleteEventGeneratorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadAlertors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/ReadAlertors',
            sora_dot_app_dot_v1beta_dot_service__pb2.ReadAlertorsRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.ReadAlertorsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAlertor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/CreateAlertor',
            sora_dot_app_dot_v1beta_dot_service__pb2.CreateAlertorRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.CreateAlertorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAlertor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/UpdateAlertor',
            sora_dot_app_dot_v1beta_dot_service__pb2.UpdateAlertorRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.UpdateAlertorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAlertor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/DeleteAlertor',
            sora_dot_app_dot_v1beta_dot_service__pb2.DeleteAlertorRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.DeleteAlertorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadAnnotators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/ReadAnnotators',
            sora_dot_app_dot_v1beta_dot_service__pb2.ReadAnnotatorsRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.ReadAnnotatorsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAnnotator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/CreateAnnotator',
            sora_dot_app_dot_v1beta_dot_service__pb2.CreateAnnotatorRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.CreateAnnotatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAnnotator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/UpdateAnnotator',
            sora_dot_app_dot_v1beta_dot_service__pb2.UpdateAnnotatorRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.UpdateAnnotatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAnnotator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/DeleteAnnotator',
            sora_dot_app_dot_v1beta_dot_service__pb2.DeleteAnnotatorRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.DeleteAnnotatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/ReadProjects',
            sora_dot_app_dot_v1beta_dot_service__pb2.ReadProjectsRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.ReadProjectsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/CreateProject',
            sora_dot_app_dot_v1beta_dot_service__pb2.CreateProjectRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.CreateProjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/UpdateProject',
            sora_dot_app_dot_v1beta_dot_service__pb2.UpdateProjectRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.UpdateProjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/DeleteProject',
            sora_dot_app_dot_v1beta_dot_service__pb2.DeleteProjectRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.DeleteProjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/ReadDevices',
            sora_dot_app_dot_v1beta_dot_service__pb2.ReadDevicesRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.ReadDevicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/CreateDevice',
            sora_dot_app_dot_v1beta_dot_service__pb2.CreateDeviceRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.CreateDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/UpdateDevice',
            sora_dot_app_dot_v1beta_dot_service__pb2.UpdateDeviceRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.UpdateDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sora.app.v1beta.AppService/DeleteDevice',
            sora_dot_app_dot_v1beta_dot_service__pb2.DeleteDeviceRequest.SerializeToString,
            sora_dot_app_dot_v1beta_dot_service__pb2.DeleteDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
